CREATE TABLE et_transaction_certificate_entity(
	id BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	transaction_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT '事务ID',
	certificate_status TINYINT (3) NOT NULL DEFAULT 0 COMMENT '凭证状态',
	created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	finished_time DATETIME DEFAULT NULL COMMENT '完成时间',
	updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	confirm_method VARCHAR (256) NOT NULL DEFAULT '' COMMENT '取消 method',
	cancel_method VARCHAR (256) NOT NULL DEFAULT '' COMMENT '取消 method',
	retry_count INT (10) NOT NULL DEFAULT 0 COMMENT '重试数',
	version INT (10) NOT NULL DEFAULT 0 COMMENT '数据版本',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '事务凭证';
